development: &non_production_settings
  site_url: http://localhost:3000
  site_name: CiteNow
  admin_email: citenow@gmail.com

test:
  <<: *non_production_settings

staging:
  site_url: http://staging.citenow.r08.railsrumble.com
  site_name: CiteNow
  admin_email: citenow@gmail.com

production:
  site_url: http://citenow.r08.railsrumble.com
  site_name: CiteNow
  admin_email: citenow@gmail.com
